/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.hope.one.common;

import java.io.Serializable;
import java.util.Date;

public class RhdShop implements Serializable {
    /**
     * rhd_budget_shop.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * rhd_budget_shop.store_no
     *
     * @mbggenerated
     */
    private String storeNo;

    /**
     * rhd_budget_shop.store_name
     *
     * @mbggenerated
     */
    private String storeName;

    /**
     * rhd_budget_shop.short_store_name
     *
     * @mbggenerated
     */
    private String shortStoreName;

    /**
     * rhd_budget_shop.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * rhd_budget_shop.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * rhd_budget_shop.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * rhd_budget_shop.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * 城市编码
     * rhd_budget_shop.city_no
     *
     * @mbggenerated
     */
    private String cityNo;

    /**
     * rhd_budget_shop.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * rhd_budget_shop.city_level
     *
     * @mbggenerated
     */
    private String cityLevel;

    /**
     * 店铺开业时间
     * rhd_budget_shop.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * 托管开始时间
     * rhd_budget_shop.tg_start_time
     *
     * @mbggenerated
     */
    private Date tgStartTime;

    /**
     * 品牌编码
     * rhd_budget_shop.brand_no
     *
     * @mbggenerated
     */
    private String brandNo;

    /**
     * rhd_budget_shop.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * 1有效0无效
     * rhd_budget_shop.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * 是否计算，1：计算  2：不计算
     * rhd_budget_shop.is_calculate
     *
     * @mbggenerated
     */
    private Byte isCalculate;

    /**
     * 数据修改时间
     * rhd_budget_shop.upt
     *
     * @mbggenerated
     */
    private Date upt;

    /**
     * 计算更新时间
     * rhd_budget_shop.calculate_upt_time
     *
     * @mbggenerated
     */
    private Date calculateUptTime;

    /**
     * 1:销售填报  2：售后填报 3：人资填报 4：财务填报 5：etl计算 6:店端基本指标提交 7:店总总体审核 8:分集团总审核 9:总部审核提交 10：店端财务2次提交
     * rhd_budget_shop.admit_stat
     *
     * @mbggenerated
     */
    private Integer admitStat;

    /**
     * 最终预算值是否已按月备份，0：未备份 1：已备份
     * rhd_budget_shop.backup_flag
     *
     * @mbggenerated
     */
    private Byte backupFlag;

    /**
     * rhd_budget_shop.lcb_store_id
     *
     * @mbggenerated
     */
    private Long lcbStoreId;

    /**
     * 对外脱敏集团编码
     * rhd_budget_shop.out_company_no
     *
     * @mbggenerated
     */
    private String outCompanyNo;

    /**
     * 对外脱敏编码
     * rhd_budget_shop.out_store_no
     *
     * @mbggenerated
     */
    private String outStoreNo;

    /**
     * 0 对标开启，1关闭(2019/10/30:废弃)
     * rhd_budget_shop.vs_enable
     *
     * @mbggenerated
     */
    private Integer vsEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rhd_budget_shop
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column rhd_budget_shop.id
     *
     * @return the value of rhd_budget_shop.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.id
     *
     * @param id the value for rhd_budget_shop.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.store_no
     *
     * @return the value of rhd_budget_shop.store_no
     *
     * @mbggenerated
     */
    public String getStoreNo() {
        return storeNo;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.store_no
     *
     * @param storeNo the value for rhd_budget_shop.store_no
     *
     * @mbggenerated
     */
    public void setStoreNo(String storeNo) {
        this.storeNo = storeNo;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.store_name
     *
     * @return the value of rhd_budget_shop.store_name
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.store_name
     *
     * @param storeName the value for rhd_budget_shop.store_name
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.short_store_name
     *
     * @return the value of rhd_budget_shop.short_store_name
     *
     * @mbggenerated
     */
    public String getShortStoreName() {
        return shortStoreName;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.short_store_name
     *
     * @param shortStoreName the value for rhd_budget_shop.short_store_name
     *
     * @mbggenerated
     */
    public void setShortStoreName(String shortStoreName) {
        this.shortStoreName = shortStoreName;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.company_id
     *
     * @return the value of rhd_budget_shop.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.company_id
     *
     * @param companyId the value for rhd_budget_shop.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.company_name
     *
     * @return the value of rhd_budget_shop.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.company_name
     *
     * @param companyName the value for rhd_budget_shop.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.product_name
     *
     * @return the value of rhd_budget_shop.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.product_name
     *
     * @param productName the value for rhd_budget_shop.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.province
     *
     * @return the value of rhd_budget_shop.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.province
     *
     * @param province the value for rhd_budget_shop.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * 城市编码
     * This method returns the value of the database column rhd_budget_shop.city_no
     *
     * @return the value of rhd_budget_shop.city_no
     *
     * @mbggenerated
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * 城市编码
     * This method sets the value of the database column rhd_budget_shop.city_no
     *
     * @param cityNo the value for rhd_budget_shop.city_no
     *
     * @mbggenerated
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.city
     *
     * @return the value of rhd_budget_shop.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.city
     *
     * @param city the value for rhd_budget_shop.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.city_level
     *
     * @return the value of rhd_budget_shop.city_level
     *
     * @mbggenerated
     */
    public String getCityLevel() {
        return cityLevel;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.city_level
     *
     * @param cityLevel the value for rhd_budget_shop.city_level
     *
     * @mbggenerated
     */
    public void setCityLevel(String cityLevel) {
        this.cityLevel = cityLevel;
    }

    /**
     * 店铺开业时间
     * This method returns the value of the database column rhd_budget_shop.start_time
     *
     * @return the value of rhd_budget_shop.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * 店铺开业时间
     * This method sets the value of the database column rhd_budget_shop.start_time
     *
     * @param startTime the value for rhd_budget_shop.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 托管开始时间
     * This method returns the value of the database column rhd_budget_shop.tg_start_time
     *
     * @return the value of rhd_budget_shop.tg_start_time
     *
     * @mbggenerated
     */
    public Date getTgStartTime() {
        return tgStartTime;
    }

    /**
     * 托管开始时间
     * This method sets the value of the database column rhd_budget_shop.tg_start_time
     *
     * @param tgStartTime the value for rhd_budget_shop.tg_start_time
     *
     * @mbggenerated
     */
    public void setTgStartTime(Date tgStartTime) {
        this.tgStartTime = tgStartTime;
    }

    /**
     * 品牌编码
     * This method returns the value of the database column rhd_budget_shop.brand_no
     *
     * @return the value of rhd_budget_shop.brand_no
     *
     * @mbggenerated
     */
    public String getBrandNo() {
        return brandNo;
    }

    /**
     * 品牌编码
     * This method sets the value of the database column rhd_budget_shop.brand_no
     *
     * @param brandNo the value for rhd_budget_shop.brand_no
     *
     * @mbggenerated
     */
    public void setBrandNo(String brandNo) {
        this.brandNo = brandNo;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.brand
     *
     * @return the value of rhd_budget_shop.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.brand
     *
     * @param brand the value for rhd_budget_shop.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * 1有效0无效
     * This method returns the value of the database column rhd_budget_shop.enable
     *
     * @return the value of rhd_budget_shop.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * 1有效0无效
     * This method sets the value of the database column rhd_budget_shop.enable
     *
     * @param enable the value for rhd_budget_shop.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * 是否计算，1：计算  2：不计算
     * This method returns the value of the database column rhd_budget_shop.is_calculate
     *
     * @return the value of rhd_budget_shop.is_calculate
     *
     * @mbggenerated
     */
    public Byte getIsCalculate() {
        return isCalculate;
    }

    /**
     * 是否计算，1：计算  2：不计算
     * This method sets the value of the database column rhd_budget_shop.is_calculate
     *
     * @param isCalculate the value for rhd_budget_shop.is_calculate
     *
     * @mbggenerated
     */
    public void setIsCalculate(Byte isCalculate) {
        this.isCalculate = isCalculate;
    }

    /**
     * 数据修改时间
     * This method returns the value of the database column rhd_budget_shop.upt
     *
     * @return the value of rhd_budget_shop.upt
     *
     * @mbggenerated
     */
    public Date getUpt() {
        return upt;
    }

    /**
     * 数据修改时间
     * This method sets the value of the database column rhd_budget_shop.upt
     *
     * @param upt the value for rhd_budget_shop.upt
     *
     * @mbggenerated
     */
    public void setUpt(Date upt) {
        this.upt = upt;
    }

    /**
     * 计算更新时间
     * This method returns the value of the database column rhd_budget_shop.calculate_upt_time
     *
     * @return the value of rhd_budget_shop.calculate_upt_time
     *
     * @mbggenerated
     */
    public Date getCalculateUptTime() {
        return calculateUptTime;
    }

    /**
     * 计算更新时间
     * This method sets the value of the database column rhd_budget_shop.calculate_upt_time
     *
     * @param calculateUptTime the value for rhd_budget_shop.calculate_upt_time
     *
     * @mbggenerated
     */
    public void setCalculateUptTime(Date calculateUptTime) {
        this.calculateUptTime = calculateUptTime;
    }

    /**
     * 1:销售填报  2：售后填报 3：人资填报 4：财务填报 5：etl计算 6:店端基本指标提交 7:店总总体审核 8:分集团总审核 9:总部审核提交 10：店端财务2次提交
     * This method returns the value of the database column rhd_budget_shop.admit_stat
     *
     * @return the value of rhd_budget_shop.admit_stat
     *
     * @mbggenerated
     */
    public Integer getAdmitStat() {
        return admitStat;
    }

    /**
     * 1:销售填报  2：售后填报 3：人资填报 4：财务填报 5：etl计算 6:店端基本指标提交 7:店总总体审核 8:分集团总审核 9:总部审核提交 10：店端财务2次提交
     * This method sets the value of the database column rhd_budget_shop.admit_stat
     *
     * @param admitStat the value for rhd_budget_shop.admit_stat
     *
     * @mbggenerated
     */
    public void setAdmitStat(Integer admitStat) {
        this.admitStat = admitStat;
    }

    /**
     * 最终预算值是否已按月备份，0：未备份 1：已备份
     * This method returns the value of the database column rhd_budget_shop.backup_flag
     *
     * @return the value of rhd_budget_shop.backup_flag
     *
     * @mbggenerated
     */
    public Byte getBackupFlag() {
        return backupFlag;
    }

    /**
     * 最终预算值是否已按月备份，0：未备份 1：已备份
     * This method sets the value of the database column rhd_budget_shop.backup_flag
     *
     * @param backupFlag the value for rhd_budget_shop.backup_flag
     *
     * @mbggenerated
     */
    public void setBackupFlag(Byte backupFlag) {
        this.backupFlag = backupFlag;
    }

    /**
     * This method returns the value of the database column rhd_budget_shop.lcb_store_id
     *
     * @return the value of rhd_budget_shop.lcb_store_id
     *
     * @mbggenerated
     */
    public Long getLcbStoreId() {
        return lcbStoreId;
    }

    /**
     * This method sets the value of the database column rhd_budget_shop.lcb_store_id
     *
     * @param lcbStoreId the value for rhd_budget_shop.lcb_store_id
     *
     * @mbggenerated
     */
    public void setLcbStoreId(Long lcbStoreId) {
        this.lcbStoreId = lcbStoreId;
    }

    /**
     * 对外脱敏集团编码
     * This method returns the value of the database column rhd_budget_shop.out_company_no
     *
     * @return the value of rhd_budget_shop.out_company_no
     *
     * @mbggenerated
     */
    public String getOutCompanyNo() {
        return outCompanyNo;
    }

    /**
     * 对外脱敏集团编码
     * This method sets the value of the database column rhd_budget_shop.out_company_no
     *
     * @param outCompanyNo the value for rhd_budget_shop.out_company_no
     *
     * @mbggenerated
     */
    public void setOutCompanyNo(String outCompanyNo) {
        this.outCompanyNo = outCompanyNo;
    }

    /**
     * 对外脱敏编码
     * This method returns the value of the database column rhd_budget_shop.out_store_no
     *
     * @return the value of rhd_budget_shop.out_store_no
     *
     * @mbggenerated
     */
    public String getOutStoreNo() {
        return outStoreNo;
    }

    /**
     * 对外脱敏编码
     * This method sets the value of the database column rhd_budget_shop.out_store_no
     *
     * @param outStoreNo the value for rhd_budget_shop.out_store_no
     *
     * @mbggenerated
     */
    public void setOutStoreNo(String outStoreNo) {
        this.outStoreNo = outStoreNo;
    }

    /**
     * 0 对标开启，1关闭(2019/10/30:废弃)
     * This method returns the value of the database column rhd_budget_shop.vs_enable
     *
     * @return the value of rhd_budget_shop.vs_enable
     *
     * @mbggenerated
     */
    public Integer getVsEnable() {
        return vsEnable;
    }

    /**
     * 0 对标开启，1关闭(2019/10/30:废弃)
     * This method sets the value of the database column rhd_budget_shop.vs_enable
     *
     * @param vsEnable the value for rhd_budget_shop.vs_enable
     *
     * @mbggenerated
     */
    public void setVsEnable(Integer vsEnable) {
        this.vsEnable = vsEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rhd_budget_shop
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RhdShop other = (RhdShop) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStoreNo() == null ? other.getStoreNo() == null : this.getStoreNo().equals(other.getStoreNo()))
            && (this.getStoreName() == null ? other.getStoreName() == null : this.getStoreName().equals(other.getStoreName()))
            && (this.getShortStoreName() == null ? other.getShortStoreName() == null : this.getShortStoreName().equals(other.getShortStoreName()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCityNo() == null ? other.getCityNo() == null : this.getCityNo().equals(other.getCityNo()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCityLevel() == null ? other.getCityLevel() == null : this.getCityLevel().equals(other.getCityLevel()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getTgStartTime() == null ? other.getTgStartTime() == null : this.getTgStartTime().equals(other.getTgStartTime()))
            && (this.getBrandNo() == null ? other.getBrandNo() == null : this.getBrandNo().equals(other.getBrandNo()))
            && (this.getBrand() == null ? other.getBrand() == null : this.getBrand().equals(other.getBrand()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getIsCalculate() == null ? other.getIsCalculate() == null : this.getIsCalculate().equals(other.getIsCalculate()))
            && (this.getUpt() == null ? other.getUpt() == null : this.getUpt().equals(other.getUpt()))
            && (this.getCalculateUptTime() == null ? other.getCalculateUptTime() == null : this.getCalculateUptTime().equals(other.getCalculateUptTime()))
            && (this.getAdmitStat() == null ? other.getAdmitStat() == null : this.getAdmitStat().equals(other.getAdmitStat()))
            && (this.getBackupFlag() == null ? other.getBackupFlag() == null : this.getBackupFlag().equals(other.getBackupFlag()))
            && (this.getLcbStoreId() == null ? other.getLcbStoreId() == null : this.getLcbStoreId().equals(other.getLcbStoreId()))
            && (this.getOutCompanyNo() == null ? other.getOutCompanyNo() == null : this.getOutCompanyNo().equals(other.getOutCompanyNo()))
            && (this.getOutStoreNo() == null ? other.getOutStoreNo() == null : this.getOutStoreNo().equals(other.getOutStoreNo()))
            && (this.getVsEnable() == null ? other.getVsEnable() == null : this.getVsEnable().equals(other.getVsEnable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rhd_budget_shop
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStoreNo() == null) ? 0 : getStoreNo().hashCode());
        result = prime * result + ((getStoreName() == null) ? 0 : getStoreName().hashCode());
        result = prime * result + ((getShortStoreName() == null) ? 0 : getShortStoreName().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCityNo() == null) ? 0 : getCityNo().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCityLevel() == null) ? 0 : getCityLevel().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getTgStartTime() == null) ? 0 : getTgStartTime().hashCode());
        result = prime * result + ((getBrandNo() == null) ? 0 : getBrandNo().hashCode());
        result = prime * result + ((getBrand() == null) ? 0 : getBrand().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getIsCalculate() == null) ? 0 : getIsCalculate().hashCode());
        result = prime * result + ((getUpt() == null) ? 0 : getUpt().hashCode());
        result = prime * result + ((getCalculateUptTime() == null) ? 0 : getCalculateUptTime().hashCode());
        result = prime * result + ((getAdmitStat() == null) ? 0 : getAdmitStat().hashCode());
        result = prime * result + ((getBackupFlag() == null) ? 0 : getBackupFlag().hashCode());
        result = prime * result + ((getLcbStoreId() == null) ? 0 : getLcbStoreId().hashCode());
        result = prime * result + ((getOutCompanyNo() == null) ? 0 : getOutCompanyNo().hashCode());
        result = prime * result + ((getOutStoreNo() == null) ? 0 : getOutStoreNo().hashCode());
        result = prime * result + ((getVsEnable() == null) ? 0 : getVsEnable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rhd_budget_shop
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeNo=").append(storeNo);
        sb.append(", storeName=").append(storeName);
        sb.append(", shortStoreName=").append(shortStoreName);
        sb.append(", companyId=").append(companyId);
        sb.append(", companyName=").append(companyName);
        sb.append(", productName=").append(productName);
        sb.append(", province=").append(province);
        sb.append(", cityNo=").append(cityNo);
        sb.append(", city=").append(city);
        sb.append(", cityLevel=").append(cityLevel);
        sb.append(", startTime=").append(startTime);
        sb.append(", tgStartTime=").append(tgStartTime);
        sb.append(", brandNo=").append(brandNo);
        sb.append(", brand=").append(brand);
        sb.append(", enable=").append(enable);
        sb.append(", isCalculate=").append(isCalculate);
        sb.append(", upt=").append(upt);
        sb.append(", calculateUptTime=").append(calculateUptTime);
        sb.append(", admitStat=").append(admitStat);
        sb.append(", backupFlag=").append(backupFlag);
        sb.append(", lcbStoreId=").append(lcbStoreId);
        sb.append(", outCompanyNo=").append(outCompanyNo);
        sb.append(", outStoreNo=").append(outStoreNo);
        sb.append(", vsEnable=").append(vsEnable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}