server:
  port: 5001


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.19.128:30001/devloper_mztu?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ttx2011

  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.19.128
    port: 35672
    username: ttx
    password: ttx2011
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /tumingzhi
  redis:
    database: 0
    host: 192.168.19.128
    port: 36379
    password: ttx2011

###ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html

#Mybatis
mybatis:
  mapper-locations: classpath:com/hope/one/mapper/*.xml
  type-aliases-package: com.hope.one.entity
  configuration:
    cache-enabled: true

logging:
  config: classpath:log/logback-config.xml
