CREATE TABLE `agent_invited`
(
    `id`                  bigint(20) NOT NULL COMMENT '主键id',
    `original_id`         bigint(20) NOT NULL COMMENT '原表主键',
    `clue_code`           varchar(32) NOT NULL COMMENT '线索code 风神对接用uuid',
    `crm_id`              varchar(64)  DEFAULT NULL COMMENT 'CRM线索唯一标识',
    `group_id`            int(11) NOT NULL COMMENT '店铺id',
    `group_type`          tinyint(2) NOT NULL COMMENT '店铺类型',
    `agent_micro_user_id` bigint(20) NOT NULL COMMENT '合伙人魔轮用户id',
    `activity_id`         bigint(20) DEFAULT NULL COMMENT '活动id',
    `invited_type`        tinyint(2) NOT NULL COMMENT '邀请人来源：1.活动；2.风神殿',
    `micro_user_id`       bigint(20) NOT NULL COMMENT '线索用户id',
    `user_name`           varchar(20) NOT NULL COMMENT '被邀请人用户名',
    `user_mobile`         varchar(50) NOT NULL COMMENT '被邀请人手机号',
    `car_number`          tinyint(4) DEFAULT '0' COMMENT '成交车辆数',
    `target_car_id`       bigint(20) DEFAULT NULL COMMENT '意向车型id',
    `target_car_type`     varchar(30)  DEFAULT NULL COMMENT '意向车型',
    `target_store_id`     bigint(20) DEFAULT NULL COMMENT '意向经销商',
    `target_store_name`   varchar(50)  DEFAULT NULL COMMENT '意向经销商名称',
    `valid_status`        tinyint(2) DEFAULT '0' COMMENT '线索状态0:无效1:有效',
    `process_status`      tinyint(2) DEFAULT '0' COMMENT '发送处理状态：0-未处理 1-发送处理中 2-发送处理完成',
    `send_status`         tinyint(2) DEFAULT NULL COMMENT '发送CRM状态，发送结果：1-检查失败，不发送 2-发送成功 3-发送失败',
    `send_result`         varchar(500) DEFAULT NULL COMMENT '发送CRM结果描述',
    `send_time`           bigint(20) DEFAULT NULL COMMENT '发送CRM时间',
    `deleted`             tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 0-未删除 1-已删除',
    `created_time`        bigint(20) NOT NULL COMMENT '创建时间',
    `updated_time`        bigint(20) NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`) USING BTREE,
    KEY                   `idx_clue_code` (`clue_code`) USING BTREE COMMENT '用户线索id',
    KEY                   `idx_original_id` (`original_id`) USING BTREE COMMENT 'id筛选'
) COMMENT='被邀请人表';