/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.hope.one.entity;

import java.util.ArrayList;
import java.util.List;

public class IndicatorMeterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public IndicatorMeterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indicator_meter
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeIsNull() {
            addCriterion("indicator_code is null");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeIsNotNull() {
            addCriterion("indicator_code is not null");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeEqualTo(String value) {
            addCriterion("indicator_code =", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeNotEqualTo(String value) {
            addCriterion("indicator_code <>", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeGreaterThan(String value) {
            addCriterion("indicator_code >", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("indicator_code >=", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeLessThan(String value) {
            addCriterion("indicator_code <", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeLessThanOrEqualTo(String value) {
            addCriterion("indicator_code <=", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeLike(String value) {
            addCriterion("indicator_code like", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeNotLike(String value) {
            addCriterion("indicator_code not like", value, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeIn(List<String> values) {
            addCriterion("indicator_code in", values, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeNotIn(List<String> values) {
            addCriterion("indicator_code not in", values, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeBetween(String value1, String value2) {
            addCriterion("indicator_code between", value1, value2, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorCodeNotBetween(String value1, String value2) {
            addCriterion("indicator_code not between", value1, value2, "indicatorCode");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameIsNull() {
            addCriterion("indicator_name is null");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameIsNotNull() {
            addCriterion("indicator_name is not null");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameEqualTo(String value) {
            addCriterion("indicator_name =", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameNotEqualTo(String value) {
            addCriterion("indicator_name <>", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameGreaterThan(String value) {
            addCriterion("indicator_name >", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("indicator_name >=", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameLessThan(String value) {
            addCriterion("indicator_name <", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameLessThanOrEqualTo(String value) {
            addCriterion("indicator_name <=", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameLike(String value) {
            addCriterion("indicator_name like", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameNotLike(String value) {
            addCriterion("indicator_name not like", value, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameIn(List<String> values) {
            addCriterion("indicator_name in", values, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameNotIn(List<String> values) {
            addCriterion("indicator_name not in", values, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameBetween(String value1, String value2) {
            addCriterion("indicator_name between", value1, value2, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andIndicatorNameNotBetween(String value1, String value2) {
            addCriterion("indicator_name not between", value1, value2, "indicatorName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMatchRulesIsNull() {
            addCriterion("match_rules is null");
            return (Criteria) this;
        }

        public Criteria andMatchRulesIsNotNull() {
            addCriterion("match_rules is not null");
            return (Criteria) this;
        }

        public Criteria andMatchRulesEqualTo(String value) {
            addCriterion("match_rules =", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesNotEqualTo(String value) {
            addCriterion("match_rules <>", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesGreaterThan(String value) {
            addCriterion("match_rules >", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesGreaterThanOrEqualTo(String value) {
            addCriterion("match_rules >=", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesLessThan(String value) {
            addCriterion("match_rules <", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesLessThanOrEqualTo(String value) {
            addCriterion("match_rules <=", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesLike(String value) {
            addCriterion("match_rules like", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesNotLike(String value) {
            addCriterion("match_rules not like", value, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesIn(List<String> values) {
            addCriterion("match_rules in", values, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesNotIn(List<String> values) {
            addCriterion("match_rules not in", values, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesBetween(String value1, String value2) {
            addCriterion("match_rules between", value1, value2, "matchRules");
            return (Criteria) this;
        }

        public Criteria andMatchRulesNotBetween(String value1, String value2) {
            addCriterion("match_rules not between", value1, value2, "matchRules");
            return (Criteria) this;
        }

        public Criteria andValueFieldIsNull() {
            addCriterion("value_field is null");
            return (Criteria) this;
        }

        public Criteria andValueFieldIsNotNull() {
            addCriterion("value_field is not null");
            return (Criteria) this;
        }

        public Criteria andValueFieldEqualTo(String value) {
            addCriterion("value_field =", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotEqualTo(String value) {
            addCriterion("value_field <>", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldGreaterThan(String value) {
            addCriterion("value_field >", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldGreaterThanOrEqualTo(String value) {
            addCriterion("value_field >=", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLessThan(String value) {
            addCriterion("value_field <", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLessThanOrEqualTo(String value) {
            addCriterion("value_field <=", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldLike(String value) {
            addCriterion("value_field like", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotLike(String value) {
            addCriterion("value_field not like", value, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldIn(List<String> values) {
            addCriterion("value_field in", values, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotIn(List<String> values) {
            addCriterion("value_field not in", values, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldBetween(String value1, String value2) {
            addCriterion("value_field between", value1, value2, "valueField");
            return (Criteria) this;
        }

        public Criteria andValueFieldNotBetween(String value1, String value2) {
            addCriterion("value_field not between", value1, value2, "valueField");
            return (Criteria) this;
        }

        public Criteria andSqlIsNull() {
            addCriterion("`sql` is null");
            return (Criteria) this;
        }

        public Criteria andSqlIsNotNull() {
            addCriterion("`sql` is not null");
            return (Criteria) this;
        }

        public Criteria andSqlEqualTo(String value) {
            addCriterion("`sql` =", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotEqualTo(String value) {
            addCriterion("`sql` <>", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlGreaterThan(String value) {
            addCriterion("`sql` >", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlGreaterThanOrEqualTo(String value) {
            addCriterion("`sql` >=", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLessThan(String value) {
            addCriterion("`sql` <", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLessThanOrEqualTo(String value) {
            addCriterion("`sql` <=", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlLike(String value) {
            addCriterion("`sql` like", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotLike(String value) {
            addCriterion("`sql` not like", value, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlIn(List<String> values) {
            addCriterion("`sql` in", values, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotIn(List<String> values) {
            addCriterion("`sql` not in", values, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlBetween(String value1, String value2) {
            addCriterion("`sql` between", value1, value2, "sql");
            return (Criteria) this;
        }

        public Criteria andSqlNotBetween(String value1, String value2) {
            addCriterion("`sql` not between", value1, value2, "sql");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Long value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Long value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Long value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Long value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Long> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Long> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Long value1, Long value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNull() {
            addCriterion("group_type is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNotNull() {
            addCriterion("group_type is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeEqualTo(Byte value) {
            addCriterion("group_type =", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotEqualTo(Byte value) {
            addCriterion("group_type <>", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThan(Byte value) {
            addCriterion("group_type >", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("group_type >=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThan(Byte value) {
            addCriterion("group_type <", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThanOrEqualTo(Byte value) {
            addCriterion("group_type <=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIn(List<Byte> values) {
            addCriterion("group_type in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotIn(List<Byte> values) {
            addCriterion("group_type not in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeBetween(Byte value1, Byte value2) {
            addCriterion("group_type between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("group_type not between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Long value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Long value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Long value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Long value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Long> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Long> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Long value1, Long value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indicator_meter
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table indicator_meter
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}