/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.hope.one.entity;

import java.io.Serializable;

public class IndicatorMeter implements Serializable {
    /**
     * indicator_meter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 监控指标编码
     * indicator_meter.indicator_code
     *
     * @mbggenerated
     */
    private String indicatorCode;

    /**
     * 监控指标名称
     * indicator_meter.indicator_name
     *
     * @mbggenerated
     */
    private String indicatorName;

    /**
     * 监控指标类型：counter，gauge，distribution_summary
     * indicator_meter.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * 匹配规则，决定是否处理指标注册和更新
     * indicator_meter.match_rules
     *
     * @mbggenerated
     */
    private String matchRules;

    /**
     * 指标值字段
     * indicator_meter.value_field
     *
     * @mbggenerated
     */
    private String valueField;

    /**
     * 查询SQL
     * indicator_meter.sql
     *
     * @mbggenerated
     */
    private String sql;

    /**
     * 店铺ID
     * indicator_meter.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * 店铺类型
     * indicator_meter.group_type
     *
     * @mbggenerated
     */
    private Byte groupType;

    /**
     * 是否删除 1删除 0未删除
     * indicator_meter.deleted
     *
     * @mbggenerated
     */
    private Byte deleted;

    /**
     * 创建时间
     * indicator_meter.created_time
     *
     * @mbggenerated
     */
    private Long createdTime;

    /**
     * 更新时间
     * indicator_meter.updated_time
     *
     * @mbggenerated
     */
    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column indicator_meter.id
     *
     * @return the value of indicator_meter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column indicator_meter.id
     *
     * @param id the value for indicator_meter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 监控指标编码
     * This method returns the value of the database column indicator_meter.indicator_code
     *
     * @return the value of indicator_meter.indicator_code
     *
     * @mbggenerated
     */
    public String getIndicatorCode() {
        return indicatorCode;
    }

    /**
     * 监控指标编码
     * This method sets the value of the database column indicator_meter.indicator_code
     *
     * @param indicatorCode the value for indicator_meter.indicator_code
     *
     * @mbggenerated
     */
    public void setIndicatorCode(String indicatorCode) {
        this.indicatorCode = indicatorCode;
    }

    /**
     * 监控指标名称
     * This method returns the value of the database column indicator_meter.indicator_name
     *
     * @return the value of indicator_meter.indicator_name
     *
     * @mbggenerated
     */
    public String getIndicatorName() {
        return indicatorName;
    }

    /**
     * 监控指标名称
     * This method sets the value of the database column indicator_meter.indicator_name
     *
     * @param indicatorName the value for indicator_meter.indicator_name
     *
     * @mbggenerated
     */
    public void setIndicatorName(String indicatorName) {
        this.indicatorName = indicatorName;
    }

    /**
     * 监控指标类型：counter，gauge，distribution_summary
     * This method returns the value of the database column indicator_meter.type
     *
     * @return the value of indicator_meter.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * 监控指标类型：counter，gauge，distribution_summary
     * This method sets the value of the database column indicator_meter.type
     *
     * @param type the value for indicator_meter.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * 匹配规则，决定是否处理指标注册和更新
     * This method returns the value of the database column indicator_meter.match_rules
     *
     * @return the value of indicator_meter.match_rules
     *
     * @mbggenerated
     */
    public String getMatchRules() {
        return matchRules;
    }

    /**
     * 匹配规则，决定是否处理指标注册和更新
     * This method sets the value of the database column indicator_meter.match_rules
     *
     * @param matchRules the value for indicator_meter.match_rules
     *
     * @mbggenerated
     */
    public void setMatchRules(String matchRules) {
        this.matchRules = matchRules;
    }

    /**
     * 指标值字段
     * This method returns the value of the database column indicator_meter.value_field
     *
     * @return the value of indicator_meter.value_field
     *
     * @mbggenerated
     */
    public String getValueField() {
        return valueField;
    }

    /**
     * 指标值字段
     * This method sets the value of the database column indicator_meter.value_field
     *
     * @param valueField the value for indicator_meter.value_field
     *
     * @mbggenerated
     */
    public void setValueField(String valueField) {
        this.valueField = valueField;
    }

    /**
     * 查询SQL
     * This method returns the value of the database column indicator_meter.sql
     *
     * @return the value of indicator_meter.sql
     *
     * @mbggenerated
     */
    public String getSql() {
        return sql;
    }

    /**
     * 查询SQL
     * This method sets the value of the database column indicator_meter.sql
     *
     * @param sql the value for indicator_meter.sql
     *
     * @mbggenerated
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * 店铺ID
     * This method returns the value of the database column indicator_meter.group_id
     *
     * @return the value of indicator_meter.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * 店铺ID
     * This method sets the value of the database column indicator_meter.group_id
     *
     * @param groupId the value for indicator_meter.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 店铺类型
     * This method returns the value of the database column indicator_meter.group_type
     *
     * @return the value of indicator_meter.group_type
     *
     * @mbggenerated
     */
    public Byte getGroupType() {
        return groupType;
    }

    /**
     * 店铺类型
     * This method sets the value of the database column indicator_meter.group_type
     *
     * @param groupType the value for indicator_meter.group_type
     *
     * @mbggenerated
     */
    public void setGroupType(Byte groupType) {
        this.groupType = groupType;
    }

    /**
     * 是否删除 1删除 0未删除
     * This method returns the value of the database column indicator_meter.deleted
     *
     * @return the value of indicator_meter.deleted
     *
     * @mbggenerated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * 是否删除 1删除 0未删除
     * This method sets the value of the database column indicator_meter.deleted
     *
     * @param deleted the value for indicator_meter.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * 创建时间
     * This method returns the value of the database column indicator_meter.created_time
     *
     * @return the value of indicator_meter.created_time
     *
     * @mbggenerated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * 创建时间
     * This method sets the value of the database column indicator_meter.created_time
     *
     * @param createdTime the value for indicator_meter.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 更新时间
     * This method returns the value of the database column indicator_meter.updated_time
     *
     * @return the value of indicator_meter.updated_time
     *
     * @mbggenerated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 更新时间
     * This method sets the value of the database column indicator_meter.updated_time
     *
     * @param updatedTime the value for indicator_meter.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IndicatorMeter other = (IndicatorMeter) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIndicatorCode() == null ? other.getIndicatorCode() == null : this.getIndicatorCode().equals(other.getIndicatorCode()))
            && (this.getIndicatorName() == null ? other.getIndicatorName() == null : this.getIndicatorName().equals(other.getIndicatorName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getMatchRules() == null ? other.getMatchRules() == null : this.getMatchRules().equals(other.getMatchRules()))
            && (this.getValueField() == null ? other.getValueField() == null : this.getValueField().equals(other.getValueField()))
            && (this.getSql() == null ? other.getSql() == null : this.getSql().equals(other.getSql()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getGroupType() == null ? other.getGroupType() == null : this.getGroupType().equals(other.getGroupType()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIndicatorCode() == null) ? 0 : getIndicatorCode().hashCode());
        result = prime * result + ((getIndicatorName() == null) ? 0 : getIndicatorName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getMatchRules() == null) ? 0 : getMatchRules().hashCode());
        result = prime * result + ((getValueField() == null) ? 0 : getValueField().hashCode());
        result = prime * result + ((getSql() == null) ? 0 : getSql().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getGroupType() == null) ? 0 : getGroupType().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator_meter
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", indicatorCode=").append(indicatorCode);
        sb.append(", indicatorName=").append(indicatorName);
        sb.append(", type=").append(type);
        sb.append(", matchRules=").append(matchRules);
        sb.append(", valueField=").append(valueField);
        sb.append(", sql=").append(sql);
        sb.append(", groupId=").append(groupId);
        sb.append(", groupType=").append(groupType);
        sb.append(", deleted=").append(deleted);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}